Add i18n support
denschub/chrome-mask pull request #3
Opened 2024-07-19 16:33 UTC by dannycolin

This patch adds support for internationalization.

2024-07-22 21:41 UTC, denschub requested changes
Good work, thanks for working on this!

The title update is broken (see inline-comment), and `npm run lint` please.

2024-07-22 21:41 UTC, denschub commented on src/background_script.js
> +      title: browser.i18n.getMessage("statusOn")
The string here is called `maskStatusOn`. Same with the off state below.

2024-07-23 00:40 UTC, denschub approved these changes

2024-07-23 00:41 UTC, merged

2024-07-23 00:41 UTC, denschub commented
Thanks! I won't release this now, but I'll try to get this translated into German soon, and maybe I'll push a release then!

2024-07-23 00:47 UTC, dannycolin commented
> Thanks! I won't release this now, but I'll try to get this translated into German soon, and maybe I'll push a release then!

Sounds good. I'll try to translate it in French before end of week ;)